class LanguageManager {
  static const String ENGLISH = 'english';
  static const String THAI = 'thai';

  static const Map<String, Map<String, String>> translations = {
    ENGLISH: {
      'welcome': 'Welcome to MedMate!',
      'add_medication': 'Add Medication',
      'medication_name': 'Medication Name',
      'enter_medication_name': 'Enter medication name',
      'reminder_time': 'Reminder Time',
      'add_another_time': '+ Add another time',
      'frequency': 'Frequency',
      'days_of_week': 'Days of the week',
      'time_range': 'Time range',
      'cycle': 'Cycle',
      'meal_timing': 'Meal Timing',
      'before': 'Before',
      'after': 'After',
      'anytime': 'Anytime',
      'start_date': 'Start date',
      'end_date': 'End date (optional)',
      'save': 'Save',
      'medication_added': 'Medication added!',
      'reminders': 'Reminders',
      'history': 'History',
      'profile': 'Profile',
      'confirm': 'Confirm',
      'confirmed': 'confirmed!',
      'adherence_rate': 'Adherence Rate',
      '5_taken': '5 taken',
      '1_missed': '1 missed',
      '6_total': '6 total',
      'today': 'Today',
      'scheduled_for': 'Scheduled for',
      'taken': 'Taken',
      'missed': 'Missed',
      'taken_at': 'Taken at',
      'language': 'Language',
      'as_needed': 'As needed',
    },
    THAI: {
      'welcome': 'ยินดีต้อนรับสู่ MedMate!',
      'add_medication': 'เพิ่มยา',
      'medication_name': 'ชื่อยา',
      'enter_medication_name': 'ป้อนชื่อยา',
      'reminder_time': 'เวลาแจ้งเตือน',
      'add_another_time': '+ เพิ่มเวลาอื่น',
      'frequency': 'ความถี่',
      'days_of_week': 'วันของสัปดาห์',
      'time_range': 'ช่วงเวลา',
      'cycle': 'รอบ',
      'meal_timing': 'เวลาของการรับประทานอาหาร',
      'before': 'ก่อนหน้า',
      'after': 'หลังจาก',
      'anytime': 'ตลอดเวลา',
      'start_date': 'วันที่เริ่มต้น',
      'end_date': 'วันที่สิ้นสุด (ไม่จำเป็น)',
      'save': 'บันทึก',
      'medication_added': 'เพิ่มยาแล้ว!',
      'reminders': 'การแจ้งเตือน',
      'history': 'ประวัติ',
      'profile': 'โปรไฟล์',
      'confirm': 'ยืนยัน',
      'confirmed': 'ยืนยันแล้ว!',
      'adherence_rate': 'อัตราการปฏิบัติตามคำแนะนำ',
      '5_taken': 'ไดรับ 5 ',
      '1_missed': 'พลาด 1',
      '6_total': 'รวม 6',
      'today': 'วันนี้',
      'scheduled_for': 'กำหนดไว้ใน',
      'taken': 'ไดรับแล้ว',
      'missed': 'พลาด',
      'taken_at': 'ไดรับเมื่อ',
      'language': 'ภาษา',
      'as_needed': 'ตามต้องการ',
    },
  };

  static String getString(String key, String language) {
    return translations[language]?[key] ?? translations[ENGLISH]?[key] ?? key;
  }
}
