// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFn6FpsqfDJ1VypBVLRq4I3ukFklfX1vA',
    appId: '1:175498097401:web:cdc5477d39f2b6ea2be828',
    messagingSenderId: '175498097401',
    projectId: 'medmate-588bb',
    authDomain: 'medmate-588bb.firebaseapp.com',
    storageBucket: 'medmate-588bb.firebasestorage.app',
    measurementId: 'G-M2GKV8QJ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMjz8Byb03sT9jsM56veZeQRlZ7Yo9Ng',
    appId: '1:175498097401:android:f704580d31ea0e1b2be828',
    messagingSenderId: '175498097401',
    projectId: 'medmate-588bb',
    storageBucket: 'medmate-588bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOMErba5o80WerAiIeIt0WUXeu1miPCZ8',
    appId: '1:175498097401:ios:b5c3bf713bbd4ace2be828',
    messagingSenderId: '175498097401',
    projectId: 'medmate-588bb',
    storageBucket: 'medmate-588bb.firebasestorage.app',
    iosBundleId: 'com.example.medmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOMErba5o80WerAiIeIt0WUXeu1miPCZ8',
    appId: '1:175498097401:ios:b5c3bf713bbd4ace2be828',
    messagingSenderId: '175498097401',
    projectId: 'medmate-588bb',
    storageBucket: 'medmate-588bb.firebasestorage.app',
    iosBundleId: 'com.example.medmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFn6FpsqfDJ1VypBVLRq4I3ukFklfX1vA',
    appId: '1:175498097401:web:d9c21b005a6132022be828',
    messagingSenderId: '175498097401',
    projectId: 'medmate-588bb',
    authDomain: 'medmate-588bb.firebaseapp.com',
    storageBucket: 'medmate-588bb.firebasestorage.app',
    measurementId: 'G-BJQEQD8V3R',
  );
}
